styfle/styfle.dev

public/.well-known/keybase.txt
=> Add keybase verification

components/Navigation.tsx
https://nextjs.org/docs/api-reference/next/router
=> Fix active class with useRouter()

package.json, pages/_app.tsx, pages/_document.tsx, utils/gtag.ts, yarn.lock
=> Add google analytics

components/Footer.tsx, pages/blog/index.tsx, pages/contact.tsx
- update contact page, add image
- add image to blog page
=> Update contact page

_posts/2020-05-09-website-redesign-3.0.md, _posts/2020-05-09-website-redesign-3.md, styles/global.css
Its finally happening...a new blog post
=> Add blog post - website redesign

styles/global.css
Thanks @pacocoursey for pointing this out 😅
=> Fix green links in articles

styles/global.css
It looked strange with no padding on mobile
=> Add padding to main element for mobile

utils/github.ts
https://github.com/styfle/dad-jokes
=> Add dad joke project

styles/global.css
- Invert color of icons in dark mode
- Add table css, invert color in dark mode
- Hide top level image, not relevant
=> Fix dark mode for awesome lists

package.json, yarn.lock
https://nextjs.org/blog/next-9-5#webpack-5-support-beta
=> Enable webpack 5

pages/_document.tsx
=> Use <Html> component

package.json, pages/blog/index.tsx, utils/markdown.ts, yarn.lock
=> Bump `marked` to 4.x

next.config.js, package.json
=> Revert "Disable support for legacy browsers"

components/Layout.tsx
I need to make some more images for other pages
=> Fix twitter card

next.config.js, package.json, yarn.lock
https://nextjs.org/blog/next-12-3
=> Bump next@12.3.0

package.json, yarn.lock
=> Bump next@12.3.2-canary.17

package.json, utils/gtag.ts, yarn.lock
Unnecessary use of `any` is a big peeve of mine, so I decided to fix this for hacktoberfest!
- `yarn build` passed type-checking
=> Eliminate `any` by using actual Gtag type

components/Footer.tsx
=> Fix footer medium

components/Footer.tsx
https://docs.joinmastodon.org/user/profile/#verification
=> Add rel="me" to verify mastodon account

app/page.tsx, styles/index.module.css
Change the pulse animation to a new coinflip animation.
=> Change pulse animation to coinflip animation

app/layout.tsx, components/Analytics.tsx, package.json, yarn.lock
https://vercel.com/docs/concepts/analytics/audiences/quickstart
=> Add analytics

package.json, pnpm-lock.yaml, tsconfig.json
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/
=> Upgrade to typescript@5

package.json, pnpm-lock.yaml
https://github.com/pnpm/pnpm/releases/tag/v8.0.0
https://vercel.com/changelog/automatic-pnpm-v8-support
=> chore: bump pnpm@8.0.0

package.json, pnpm-lock.yaml
https://nextjs.org/blog/next-13-4
=> chore: bump next and pnpm

app/blog/[slug]/page.tsx, app/blog/page.tsx, app/contact/page.tsx, app/layout.tsx, app/page.tsx, app/projects/[name]/page.tsx, app/projects/page.tsx
https://nextjs.org/docs/app/api-reference/functions/generate-metadata
=> fix: remove duplicate meta tags from `<head>`

posts/2022-08-07-corepack.md
Some things have changed in the last year
=> chore: update corepack blog

next.config.js, package.json, pnpm-lock.yaml, tsconfig.json
https://react.dev/learn/react-compiler
=> chore: experimental react compiler

components/Analytics.tsx, package.json, pnpm-lock.yaml
https://vercel.com/docs/speed-insights/migrating-from-legacy
=> chore: upgrade analytics to speed-insights

app/blog/[slug]/page.tsx, app/projects/[name]/page.tsx, next-env.d.ts, next.config.ts, package.json, pnpm-lock.yaml
```
npx @next/codemod@canary upgrade latest
```
=> chore: upgrade next@15.0.0

app/contact/page.tsx, components/Footer.tsx, posts/2017-10-16-es6-modules-today-with-typescript.md, posts/2018-01-01-es6-proxy-localization.md, posts/2020-05-09-website-redesign-3.md, posts/2021-04-25-software-shepherd.md, posts/2022-08-07-corepack.md
Avoid the redirect since twitter.com is now x.com
=> twitter.com => x.com

next-env.d.ts, package.json, pnpm-lock.yaml
https://nextjs.org/blog/next-15-1
https://react.dev/blog/2024/12/05/react-19
=> chore: next@15.1.0 and react@19.0.0

package.json, pnpm-lock.yaml
=> chore: update next@15.1.4

next.config.ts, utils/github.ts
https://www.reddit.com/r/web_design/comments/10lqgja/placeholdercom_is_no_more/
=> fix: swap from `via.placeholder.com` to `placehold.co`
